### ISSUE TITLE
Two small issues!

### ISSUE THREAD

**Issue by spapas** [allender/vim-codestats#1]
Hello @allender thank you again for this plugin! I tested and debugged it a bit on my machine. There are two issues I've found:

* For some reason I didn't get any stats updated without getting any error messages; after some debugging I observerd that I got a 403 error from the codestats server. After more debugging, it seems that line 12 of codestats.vim (`let g:vim_codestats_key = ''`) overwrites for some reason my configuration; after I commeted it out it worked fine. I think instead of silently initializing that variable, a check should be addeed there and if that variable isn't configure display some error to the user

* When I swich buffers with vim, for example by using `:e otherfile` and try to edit that file I immediately get an error in the function `add_xp`: Undefined variable b:current_xp. In this function you just have `let b:current_xp += 1` however, the b:current_xp variable is only initialized once when the plugin is loaded. So I recommend adding a check there to see if the b:current_xp has a value for the current buffer, if not then initialize it first to 0 and then increase it.

These should be very quick to fix; I don't want to submit a PR because I don't have much experience with vim script but I really hope that you'll fix 'em soon so I can finally be able to use codestats with my vim on windows :)

Kind regards,
Serafeim

**Comment by allender** [comment]
Yup - both valid.   thanks for reporting

**Comment by allender** [comment]
Fixed with latest commits this morning.
